function waveform = createWaveform(type,SweepBandwidth,PulseWidth,prf,SampleRate)

    if(type == 'Rectangular')
        waveform = phased.RectangularWaveform(...
            'PulseWidth',PulseWidth,...
            'PRF',prf,...
            'SampleRate',SampleRate);
    elseif(type == 'LMF')
        waveform = phased.LinearFMWaveform(...
            'SweepBandwidth',SweepBandwidth,...
            'PulseWidth',pulse_width,...
            'PRF',prf,...
            'SampleRate',SampleRate);
    elseif(type == 'Barker')
        waveform = phased.PhaseCodedWaveform('Code','Barker',...
            'ChipWidth',PulseWidth,'NumChips',SweepBandwidth,'PRF',prf,...
            'SampleRate',SampleRate,...
            'OutputFormat','Pulses','NumPulses',1);
    end



end