function [radiator,collector] = create_RadColl(Sensor,OperatingFrequency)

    radiator = phased.Radiator(...
        'Sensor',Sensor,...
    'OperatingFrequency',OperatingFrequency);
    collector = phased.Collector(...
        'Sensor',Sensor,...
        'OperatingFrequency',OperatingFrequency);

end