function [reciever,transmitter] = create_RxTx(Gain,NoiseFigure,SampleRate,...
    Seed,peak_power)

    reciever = phased.ReceiverPreamp(...
        'Gain',Gain,...
        'NoiseFigure',NoiseFigure,...
        'SampleRate',SampleRate,...
        'EnableInputPort',true,'PhaseNoiseInputPort',true,...
        'SeedSource','Property','Seed',Seed);

    transmitter = phased.Transmitter(...
        'Gain',Gain,...
        'PeakPower',peak_power,...
        'InUseOutputPort',true,'CoherentOnTransmit',false,...
        'PhaseNoiseOutputPort',true);
end